const ingredientsList = {
    1: { name: "ail" },
    2: { name: "amandes" },
    3: { name: "ananas" },
    4: { name: "avocat" },
    5: { name: "basilic" },
    6: { name: "beurre" },
    7: { name: "betterave" },
    8: { name: "bouillon de légumes" },
    9: { name: "boulette de viande" },
    10: { name: "carotte" },
    11: { name: "cannelle" },
    12: { name: "courgette" },
    13: { name: "courge butternut" },
    14: { name: "crème" },
    15: { name: "dinde" },
    16: { name: "épices" },
    17: { name: "épinards" },
    18: { name: "feta" },
    19: { name: "flocons d'avoine" },
    20: { name: "fromage" },
    21: { name: "fromage frais" },
    22: { name: "fromage râpé" },
    23: { name: "fruits d’hiver" },
    24: { name: "gnocchis" },
    25: { name: "herbes" },
    26: { name: "huile d'olive" },
    27: { name: "lait" },
    28: { name: "lait de coco" },
    29: { name: "laitue" },
    30: { name: "lasagne" },
    31: { name: "lardons" },
    32: { name: "mangue" },
    33: { name: "melon" },
    34: { name: "miel" },
    35: { name: "mozzarella" },
    36: { name: "noix" },
    37: { name: "oignon" },
    38: { name: "oeuf" },
    39: { name: "pain" },
    40: { name: "pain burger" },
    41: { name: "pain complet" },
    42: { name: "parmesan" },
    43: { name: "patate douce" },
    44: { name: "pâte à pizza" },
    45: { name: "pâte feuilletée" },
    46: { name: "pesto" },
    47: { name: "poire" },
    48: { name: "poisson" },
    49: { name: "poivron" },
    50: { name: "pomme" },
    51: { name: "pommes de terre" },
    52: { name: "porridge" },
    53: { name: "poulet" },
    54: { name: "raisins" },
    55: { name: "riz" },
    56: { name: "sauce au choix" },
    57: { name: "sauce barbecue" },
    58: { name: "sauce soja" },
    59: { name: "sauce tomate" },
    60: { name: "semoule" },
    61: { name: "spaghetti" },
    62: { name: "sucre" },
    63: { name: "tacos" },
    64: { name: "tomate" },
    65: { name: "tortillas" },
    66: { name: "viande hachée" },
    67: { name: "vinaigre balsamique" },
    68: { name: "wraps" },
    69: { name: "yaourt" },
    70: { name: "yaourt grec" }
};
